version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: master
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  master_server:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/master
      SERVER_BIND: 0.0.0.0:8080
      TOKEN_TTL_HOURS: 720
      OTP_REQUIRED: "false"
      RUST_LOG: master_server=debug,tower_http=debug
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
