[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-orm-migration = "1.1"

[dependencies.sea-orm]
version = "1.1"
features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
]
